# Generated by Django 3.1 on 2022-07-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_auto_20220710_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 20, 55, 29, 844881)),
        ),
    ]
