# Generated by Django 3.1 on 2022-07-11 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0007_auto_20220710_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
